// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KPCOS.Data.Models;

public partial class DesignTemplate
{

    public string Id { get; set; }
    [Required]
    public string DefaultLocation { get; set; }
    [Required]
    public string DefaultShape { get; set; }
    [Required]
    public string DefaultSize { get; set; }
    [Required]
    public string Description { get; set; }
    [Required]
    public string Image { get; set; }
    [Required]
    public string Name { get; set; }

    public decimal? TotalPrice { get; set; }

    public virtual ICollection<Design> Designs { get; set; } = new List<Design>();
}