// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace KPCOS.Data.Models;

public partial class FA24_SE1717_PRN231_G4_KPCOSContext : DbContext
{
    public FA24_SE1717_PRN231_G4_KPCOSContext()
    {
    }

    public FA24_SE1717_PRN231_G4_KPCOSContext(DbContextOptions<FA24_SE1717_PRN231_G4_KPCOSContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Consultation> Consultations { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Design> Designs { get; set; }

    public virtual DbSet<DesignConcept> DesignConcepts { get; set; }

    public virtual DbSet<DesignTemplate> DesignTemplates { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Feedback> Feedbacks { get; set; }

    public virtual DbSet<Invoice> Invoices { get; set; }

    public virtual DbSet<Material> Materials { get; set; }

    public virtual DbSet<Package> Packages { get; set; }

    public virtual DbSet<PaymentPolicy> PaymentPolicies { get; set; }

    public virtual DbSet<Project> Projects { get; set; }

    public virtual DbSet<Quotation> Quotations { get; set; }

    public virtual DbSet<ServiceAssignment> ServiceAssignments { get; set; }

    public virtual DbSet<ServiceBooking> ServiceBookings { get; set; }

    public virtual DbSet<ServiceExecution> ServiceExecutions { get; set; }

    public virtual DbSet<ServiceFeedback> ServiceFeedbacks { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Consultation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Consulta__3213E83F1A2FF1D7");

            entity.ToTable("Consultation");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.AdjustedDesign)
                .HasColumnType("text")
                .HasColumnName("adjusted_design");
            entity.Property(e => e.AdjustedSpecification)
                .HasColumnType("text")
                .HasColumnName("adjusted_specification");
            entity.Property(e => e.DesignId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("design_id");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");

            entity.HasOne(d => d.Design).WithMany(p => p.Consultations)
                .HasForeignKey(d => d.DesignId)
                .HasConstraintName("FK_Consultation_Design");
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Customer__3213E83FAA299BC7");

            entity.ToTable("Customer");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.LoyaltyPoint).HasColumnName("loyalty_point");
            entity.Property(e => e.MembershipStatus)
                .HasMaxLength(50)
                .HasColumnName("membership_status");
            entity.Property(e => e.PackageId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("package_id");
            entity.Property(e => e.UserId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("user_id");

            entity.HasOne(d => d.Package).WithMany(p => p.Customers)
                .HasForeignKey(d => d.PackageId)
                .HasConstraintName("FK_Customer_Package");

            entity.HasOne(d => d.User).WithMany(p => p.Customers)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Customer_User");
        });

        modelBuilder.Entity<Design>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Design__3213E83FE5726A41");

            entity.ToTable("Design");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.Budget)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("budget");
            entity.Property(e => e.ConsultantBy)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("consultant_by");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("customer_id");
            entity.Property(e => e.Depth)
                .HasDefaultValue(0.6m)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("depth");
            entity.Property(e => e.DesignType)
                .HasMaxLength(50)
                .HasColumnName("design_type");
            entity.Property(e => e.FiltrationSystem)
                .HasMaxLength(50)
                .HasColumnName("filtration_system");
            entity.Property(e => e.KoiCountRange)
                .HasMaxLength(50)
                .HasColumnName("koi_count_range");
            entity.Property(e => e.KoiType)
                .HasMaxLength(50)
                .HasColumnName("koi_type");
            entity.Property(e => e.Location)
                .HasMaxLength(50)
                .HasDefaultValue("Outdoor")
                .HasColumnName("location");
            entity.Property(e => e.MinLength)
                .HasDefaultValue(2m)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("min_length");
            entity.Property(e => e.MinWidth)
                .HasDefaultValue(0.8m)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("min_width");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.Shape)
                .HasMaxLength(50)
                .HasDefaultValue("Rectangular")
                .HasColumnName("shape");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Not yet responded")
                .HasColumnName("status");
            entity.Property(e => e.TemplateId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("template_id");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("update_date");
            entity.Property(e => e.WaterLevel)
                .HasDefaultValue(0.4m)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("water_level");
            entity.Property(e => e.WaterQuality)
                .HasMaxLength(50)
                .HasColumnName("water_quality");

            entity.HasOne(d => d.Customer).WithMany(p => p.Designs)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Design_Customer");

            entity.HasOne(d => d.Template).WithMany(p => p.Designs)
                .HasForeignKey(d => d.TemplateId)
                .HasConstraintName("FK_Design_Template");
        });

        modelBuilder.Entity<DesignConcept>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DesignCo__3213E83F11AE8A1B");

            entity.ToTable("DesignConcept");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Image)
                .HasMaxLength(255)
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ProjectId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("project_id");

            entity.HasOne(d => d.Project).WithMany(p => p.DesignConcepts)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK_DesignConcept_Project");
        });

        modelBuilder.Entity<DesignTemplate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DesignTe__3213E83F18852BEA");

            entity.ToTable("DesignTemplate");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.DefaultLocation)
                .HasMaxLength(100)
                .HasColumnName("default_location");
            entity.Property(e => e.DefaultShape)
                .HasMaxLength(50)
                .HasColumnName("default_shape");
            entity.Property(e => e.DefaultSize)
                .HasMaxLength(50)
                .HasColumnName("default_size");
            entity.Property(e => e.Description)
                .HasColumnType("text")
                .HasColumnName("description");
            entity.Property(e => e.Image)
                .HasMaxLength(255)
                .HasColumnName("image");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.TotalPrice)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("total_price");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Employee__3213E83FEE68B788");

            entity.ToTable("Employee");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.Salary)
                .HasDefaultValue(1000m)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("salary");
            entity.Property(e => e.SupervisorId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("supervisor_id");
            entity.Property(e => e.UserId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("user_id");

            entity.HasOne(d => d.Supervisor).WithMany(p => p.InverseSupervisor)
                .HasForeignKey(d => d.SupervisorId)
                .HasConstraintName("FK_Employee_Supervisor");

            entity.HasOne(d => d.User).WithMany(p => p.Employees)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_Employee_User");
        });

        modelBuilder.Entity<Feedback>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Feedback__3213E83F96D3765A");

            entity.ToTable("Feedback");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.Content)
                .HasColumnType("text")
                .HasColumnName("content");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("customer_id");
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");
            entity.Property(e => e.ProjectId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("project_id");
            entity.Property(e => e.Rating)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("rating");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("update_date");

            entity.HasOne(d => d.Customer).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Feedback_Customer");

            entity.HasOne(d => d.Project).WithMany(p => p.Feedbacks)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK_Feedback_Project");
        });

        modelBuilder.Entity<Invoice>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Invoice__3213E83F22A1D60A");

            entity.ToTable("Invoice");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.DiscountApplied)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("discount_applied");
            entity.Property(e => e.PaymentDate)
                .HasColumnType("datetime")
                .HasColumnName("payment_date");
            entity.Property(e => e.PaymentMethod)
                .HasMaxLength(50)
                .HasColumnName("payment_method");
            entity.Property(e => e.ProjectId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("project_id");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasColumnName("status");
            entity.Property(e => e.TaxAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("tax_amount");
            entity.Property(e => e.TotalAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("total_amount");

            entity.HasOne(d => d.Project).WithMany(p => p.Invoices)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK_Invoice_Project");
        });

        modelBuilder.Entity<Material>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Material__3213E83F856B7201");

            entity.ToTable("Material");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.ProjectId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("project_id");
            entity.Property(e => e.Type)
                .HasMaxLength(50)
                .HasColumnName("type");
            entity.Property(e => e.Unit)
                .HasMaxLength(50)
                .HasColumnName("unit");

            entity.HasOne(d => d.Project).WithMany(p => p.Materials)
                .HasForeignKey(d => d.ProjectId)
                .HasConstraintName("FK_Material_Project");
        });

        modelBuilder.Entity<Package>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Package__3213E83F7A66ECD3");

            entity.ToTable("Package");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.DiscountPercentage).HasColumnName("discount_percentage");
            entity.Property(e => e.Duration)
                .HasMaxLength(50)
                .HasColumnName("duration");
            entity.Property(e => e.FeatureInclude)
                .HasColumnType("text")
                .HasColumnName("feature_include");
            entity.Property(e => e.IsActive).HasColumnName("is_active");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Price)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("price");
            entity.Property(e => e.UpdateAt)
                .HasColumnType("datetime")
                .HasColumnName("update_at");
        });

        modelBuilder.Entity<PaymentPolicy>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__PaymentP__3213E83FB2EE6900");

            entity.ToTable("PaymentPolicy");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.Description)
                .HasMaxLength(255)
                .HasColumnName("description");
            entity.Property(e => e.Name)
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.PaymentDeadlineDay).HasColumnName("payment_deadline_day");
            entity.Property(e => e.PaymentMethodAvailable)
                .HasColumnType("text")
                .HasColumnName("payment_method_available");
            entity.Property(e => e.RefundPolicy)
                .HasColumnType("text")
                .HasColumnName("refund_policy");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("update_date");
        });

        modelBuilder.Entity<Project>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Project__3213E83F66C9E3A2");

            entity.ToTable("Project");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.ActualCost)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("actual_cost");
            entity.Property(e => e.ConstructionStaffId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("construction_staff_id");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("customer_id");
            entity.Property(e => e.DesignerId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("designer_id");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.EstimatedCost)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("estimated_cost");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.Status)
                .HasMaxLength(20)
                .HasColumnName("status");

            entity.HasOne(d => d.ConstructionStaff).WithMany(p => p.ProjectConstructionStaffs)
                .HasForeignKey(d => d.ConstructionStaffId)
                .HasConstraintName("FK_Project_ConstructionStaff");

            entity.HasOne(d => d.Customer).WithMany(p => p.Projects)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Project_Customer");

            entity.HasOne(d => d.Designer).WithMany(p => p.ProjectDesigners)
                .HasForeignKey(d => d.DesignerId)
                .HasConstraintName("FK_Project_Designer");
        });

        modelBuilder.Entity<Quotation>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Quotatio__3213E83FF9F2486B");

            entity.ToTable("Quotation");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.ComplexityLevel)
                .HasMaxLength(50)
                .HasColumnName("complexity_level");
            entity.Property(e => e.ConsultationAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("consultation_amount");
            entity.Property(e => e.DesignId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("design_id");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.QuotationAmount)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("quotation_amount");
            entity.Property(e => e.QuotationDate)
                .HasColumnType("datetime")
                .HasColumnName("quotation_date");
            entity.Property(e => e.Scale)
                .HasMaxLength(50)
                .HasColumnName("scale");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasColumnName("status");
            entity.Property(e => e.Style)
                .HasMaxLength(100)
                .HasColumnName("style");

            entity.HasOne(d => d.Design).WithMany(p => p.Quotations)
                .HasForeignKey(d => d.DesignId)
                .HasConstraintName("FK_Quotation_Design");
        });

        modelBuilder.Entity<ServiceAssignment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceA__3213E83FEBA0D20E");

            entity.ToTable("ServiceAssignment");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.AssignDate)
                .HasColumnType("datetime")
                .HasColumnName("assign_date");
            entity.Property(e => e.EmployeeId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("employee_id");
            entity.Property(e => e.ServiceBookingId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("service_booking_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Assigned")
                .HasColumnName("status");

            entity.HasOne(d => d.Employee).WithMany(p => p.ServiceAssignments)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_ServiceAssignment_Employee");

            entity.HasOne(d => d.ServiceBooking).WithMany(p => p.ServiceAssignments)
                .HasForeignKey(d => d.ServiceBookingId)
                .HasConstraintName("FK_ServiceAssignment_ServiceBooking");
        });

        modelBuilder.Entity<ServiceBooking>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceB__3213E83FDB2F72FC");

            entity.ToTable("ServiceBooking");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.BookingDate)
                .HasColumnType("datetime")
                .HasColumnName("booking_date");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("customer_id");
            entity.Property(e => e.EndDate)
                .HasColumnType("datetime")
                .HasColumnName("end_date");
            entity.Property(e => e.Note)
                .HasColumnType("text")
                .HasColumnName("note");
            entity.Property(e => e.ScheduleType)
                .HasMaxLength(50)
                .HasColumnName("schedule_type");
            entity.Property(e => e.ServiceType)
                .HasMaxLength(50)
                .HasColumnName("service_type");
            entity.Property(e => e.StartDate)
                .HasColumnType("datetime")
                .HasColumnName("start_date");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Pending")
                .HasColumnName("status");

            entity.HasOne(d => d.Customer).WithMany(p => p.ServiceBookings)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_ServiceBooking_Customer");
        });

        modelBuilder.Entity<ServiceExecution>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceE__3213E83FD27E75A1");

            entity.ToTable("ServiceExecution");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.EmployeeId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("employee_id");
            entity.Property(e => e.ExecutionDate)
                .HasColumnType("datetime")
                .HasColumnName("execution_date");
            entity.Property(e => e.Result)
                .HasColumnType("text")
                .HasColumnName("result");
            entity.Property(e => e.ServiceBookingId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("service_booking_id");
            entity.Property(e => e.Status)
                .HasMaxLength(50)
                .HasDefaultValue("Completed")
                .HasColumnName("status");

            entity.HasOne(d => d.Employee).WithMany(p => p.ServiceExecutions)
                .HasForeignKey(d => d.EmployeeId)
                .HasConstraintName("FK_ServiceExecution_Employee");

            entity.HasOne(d => d.ServiceBooking).WithMany(p => p.ServiceExecutions)
                .HasForeignKey(d => d.ServiceBookingId)
                .HasConstraintName("FK_ServiceExecution_ServiceBooking");
        });

        modelBuilder.Entity<ServiceFeedback>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ServiceF__3213E83FE23E258A");

            entity.ToTable("ServiceFeedback");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.CustomerId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("customer_id");
            entity.Property(e => e.Feedback)
                .HasColumnType("text")
                .HasColumnName("feedback");
            entity.Property(e => e.Rating)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("rating");
            entity.Property(e => e.ServiceBookingId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("service_booking_id");

            entity.HasOne(d => d.Customer).WithMany(p => p.ServiceFeedbacks)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_ServiceFeedback_Customer");

            entity.HasOne(d => d.ServiceBooking).WithMany(p => p.ServiceFeedbacks)
                .HasForeignKey(d => d.ServiceBookingId)
                .HasConstraintName("FK_ServiceFeedback_ServiceBooking");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__User__3213E83F3193F61C");

            entity.ToTable("User");

            entity.Property(e => e.Id)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.Fullname)
                .HasMaxLength(100)
                .HasColumnName("fullname");
            entity.Property(e => e.Password)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("password");
            entity.Property(e => e.Phone)
                .HasMaxLength(15)
                .HasColumnName("phone");
            entity.Property(e => e.Role)
                .HasMaxLength(50)
                .HasColumnName("role");
            entity.Property(e => e.Status)
                .HasDefaultValue(true)
                .HasColumnName("status");
            entity.Property(e => e.UpdateDate)
                .HasColumnType("datetime")
                .HasColumnName("update_date");
            entity.Property(e => e.Username)
                .HasMaxLength(100)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}