// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class ServiceBooking
{
    public string Id { get; set; }

    public string CustomerId { get; set; }

    public string ServiceType { get; set; }

    public DateTime? BookingDate { get; set; }

    public string ScheduleType { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public string Note { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<ServiceAssignment> ServiceAssignments { get; set; } = new List<ServiceAssignment>();

    public virtual ICollection<ServiceExecution> ServiceExecutions { get; set; } = new List<ServiceExecution>();

    public virtual ICollection<ServiceFeedback> ServiceFeedbacks { get; set; } = new List<ServiceFeedback>();
}