// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class ServiceFeedback
{
    public string Id { get; set; }

    public string ServiceBookingId { get; set; }

    public string CustomerId { get; set; }

    public decimal? Rating { get; set; }

    public string Feedback { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ServiceBooking ServiceBooking { get; set; }
}