// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class ServiceAssignment
{
    public string Id { get; set; }

    public string ServiceBookingId { get; set; }

    public string EmployeeId { get; set; }

    public DateTime? AssignDate { get; set; }

    public string Status { get; set; }

    public virtual Employee Employee { get; set; }

    public virtual ServiceBooking ServiceBooking { get; set; }
}